# Arquivo de configuração para o Netlify

[build]
  # Diretório onde as funções serverless estão localizadas
  functions = "netlify/functions"

[dev]
  # Comando para iniciar o servidor de desenvolvimento local
  # Framework #static significa que não estamos usando um gerador de site estático
  framework = "#static"
  # Porta que o Netlify Dev usará
  port = 8888
  # O Netlify precisa saber qual pasta servir. A raiz do projeto (./) contém o painel.html
  publish = "."

# Redirecionamento para que nossas funções fiquem mais bonitas de chamar.
# Em vez de /.netlify/functions/inventory, podemos chamar /api/inventory.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
